name: Build and Test App
on:
  push:
    branches:
      - main
    
defaults:
  run:
    working-directory: exercises/3-github-actions/app/.

jobs:
  Build_and_Run:
    runs-on: ubuntu-latest
    steps:
    
    - name: checkout code
      uses: actions/checkout@v5
    
    - name: set up pnpm
      uses: pnpm/action-setup@v4 
      with:
        version: 22

    - name: install dependency
      run: pnpm install 
    
    - name: view outdated packages
      run: pnpm outdated 

    - name: prettify the code
      run: pnpm prettier . --write

    - name: run tests
      run: pnpm test